CREATE TABLE TEMPERATUUR (
    id INTEGER PRIMARY KEY,
    waarde REAL NOT NULL
);

CREATE TABLE LUCHTVOCHTIGHEID (
    id INTEGER PRIMARY KEY,
    waarde REAL NOT NULL
);

CREATE TABLE LUCHTDRUK (
    id INTEGER PRIMARY KEY,
    waarde REAL NOT NULL
);

CREATE TABLE TIME (
    id INTEGER PRIMARY KEY,
    tijdstip DATETIME NOT NULL,
    temperatuur_id INTEGER NOT NULL,
    luchtvochtigheid_id INTEGER NOT NULL,
    luchtdruk_id INTEGER NOT NULL,
    FOREIGN KEY (temperatuur_id) REFERENCES TEMPERATUUR (id),
    FOREIGN KEY (luchtvochtigheid_id) REFERENCES LUCHTVOCHTIGHEID (id),
    FOREIGN KEY (luchtdruk_id) REFERENCES LUCHTDRUK (id)
);